name: dioc
description: Inversion of control based on dependency injection through containers.
version: 0.1.6
homepage: https://github.com/aloisdeniel/dioc
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

